### ISSUE TITLE
Fix Heimdall

### ISSUE THREAD

**Issue by acbgbca** [acbgbca/microserver-docker#78]
Heimdall is regularly timing out on upgrade. Need to try and fix.

**Comment by acbgbca** [comment]
Deleted the existing config and re-created. We'll see if that fixes it

**Comment by acbgbca** [comment]
Re-creating didn't work. Look at increasing the timeout for just this container. See https://stackoverflow.com/a/38631255

**Comment by AndrewBarrowAusport** [comment]
No issues since increasing the timeout. Closing this issue

**Comment by acbgbca** [comment]
No issues since increasing the timeout, closing this issue
